# OpenAPI version identifier - required for OpenAPI 3.0 domains
openapi: 3.0.0

#######################
# Optional info section
#######################
info:
  title: Dominio de convenios
  description: Dominio de convenios para Toures Balon
  version: '1.0.0'

components:

  ####################
  # Common data models
  ####################
  schemas:
  
  # Objetos
    Convenio:
      type: object
      properties:
        nombreProveedor:
          description: Nombre del proveedor de servicios.
          type: string
          minLength: 1
          maxLength: 254
        identificacion:
          description: Identificación del proveedor de servicios.
          type: string
          minLength: 1
          maxLength: 40
        tipoConvenio:
          description: Tipo de convenio.
          type: string
          enum: 
            - TRANSPORTE
            - HOSPEDAJE
            - EVENTO
        fechaVigencia:
          description: Vigencia del convenio.
          type: string
          format: date-time
        correo:
          description: Correo de contacto del convenio.
          type: string
          minLength: 1
          maxLength: 90
        pais:
          description: País de origen de operación del convenio.
          $ref: '#/components/schemas/Pais'
        ciudad:
          description: Ciudad de operación de la empresa de convenio.
          $ref: '#/components/schemas/Ciudad'
   
  ####################
  # Catalogos
  ####################
    Pais:
      description: País
      type: object
      properties:
        codigo: 
          description: Código del país.
          format: int32
          minimum: 1
          type: number
        nombre: 
          description: Nombre del país.
          type: string
          minLength: 1
          maxLength: 64
    Ciudad:
      description: Ciudad
      type: object
      properties:
        codigo: 
          description: Código de la ciudad.
          format: int32
          minimum: 1
          type: number
        nombre: 
          description: Nombre de la ciudad.
          type: string
          minLength: 1
          maxLength: 64
        pais:
          $ref: '#/components/schemas/Pais'